---

- name: get arch
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_arch_shell
  changed_when: false

- name: set arch fact
  ansible.builtin.set_fact:
    dpkg_arch: "{{ dpkg_arch_shell.stdout }}"
